|
    name: Node.js CI

    on:
      push:
        branches: [ "main" ]
      pull_request:
        branches: [ "main" ]

    jobs:
      build:

        runs-on: ubuntu-latest

        strategy:
          matrix:
            node-version: [18.x, 20.x, 22.x]

        steps:
        - uses: actions/checkout@v4
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v4
          with:
            node-version: ${{ matrix.node-version }}
            cache: 'npm'
        - run: npm ci
        - run: npm run build --if-present
        - run: npm test --if-present
        - name: Analyze with SonarCloud
          uses: sonarsource/sonarcloud-github-action@master
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        - name: Run security checks
          run: |
            npm install -g retire
            retire --node --outputformat json > retire-results.json
        - name: Upload RetireJS results
          uses: actions/upload-artifact@v3
          with:
            name: retire-results
            path: retire-results.json
        - name: Archive production artifacts
          uses: actions/upload-artifact@v3
          with:
            name: production-files
            path: |
              public/
            retention-days: 5