name: Node.js CI

 on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *' # Daily at midnight UTC

 jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install Dependencies
      run: npm ci
    - name: Lint Code
      run: npm run lint
    - name: Run Tests
      run: npm run test
    - name: Build Production Assets
      run: npm run build
    - name: Deploy to Production
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |
        echo "Deploying to Production..."
        # Add deployment script here
    - name: Security Scan
      run: |
        echo "Performing Security Scan..."
        # Integrate security scanning tools here
    - name: Dependency Check
      run: |
        echo "Checking for Vulnerable Dependencies..."
        # Integrate dependency scanning tools here
    - name: Heartbeat Check
      run: |
        echo "Checking that site is working..."
        # Ping the site and ensure its working
    - name: Check for proxy errors
      run: |
        echo "Check for proxies in proxies.json and proxies.js..."
        # ensure both are working and correct!