|
    name: Node.js CI

    on:
      push:
        branches: [ "main" ]
      pull_request:
        branches: [ "main" ]

    jobs:
      build:
        runs-on: ubuntu-latest

        strategy:
          matrix:
            node-version: [18.x, 20.x, 22.x]

        steps:
        - uses: actions/checkout@v4
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v4
          with:
            node-version: ${{ matrix.node-version }}
            cache: 'npm'

        - name: Install Dependencies
          run: npm ci

        - name: Lint
          run: npm run lint --if-present

        - name: Build
          run: npm run build --if-present

        - name: Run tests
          run: npm test --if-present
          env:
            CI: true

        - name: SonarCloud Scan
          if: github.event_name == 'push'
          uses: sonarsource/sonarcloud-github-action@master
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          with:
            args: >
              -Dsonar.organization=${{ secrets.SONARCLOUD_ORG }}
              -Dsonar.projectKey=${{ secrets.SONARCLOUD_PROJECT_KEY }}
              -Dsonar.sources=public
              -Dsonar.tests=public
              -Dsonar.javascript.lcov.reportPaths=public/coverage/lcov.info

        - name: Run security checks with Retire.js
          run: |
            npm install -g retire
            retire --node --outputformat json > public/retire-results.json
        - name: Upload RetireJS results
          if: always()
          uses: actions/upload-artifact@v3
          with:
            name: retire-results
            path: public/retire-results.json

        - name: Run custom security scan
          run: |
            echo "Running custom security scan..."
            grep -rE "(password|api_key|secret)" public/ || true
            echo "Custom security scan completed."
        - name: Archive production artifacts
          if: github.event_name == 'push' && matrix.node-version == '22.x'
          uses: actions/upload-artifact@v3
          with:
            name: production-files
            path: public/
            retention-days: 5